apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/dashboard-depl.yaml
    - ./infra/k8s/expense-depl.yaml
    - ./infra/k8s/financial-data-depl.yaml
    - ./infra/k8s/income-depl.yaml
    - ./infra/k8s/ingress-srv.yaml
    - ./infra/k8s/rabbitmq-depl.yaml
    - ./infra/k8s/smart-ai-depl.yaml
    - ./infra/k8s/user-depl.yaml
build:
  local:
    push: false
  artifacts:
    - image: ashuz057/expensio-user
      context: ./services/user
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: ashuz057/expensio-expense
      context: ./services/expense
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: ashuz057/expensio-financial-data
      context: ./services/financial-data
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: ashuz057/expensio-income
      context: ./services/income
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: ashuz057/expensio-dashboard
      context: ./services/dashboard
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: ashuz057/expensio-smart-ai
      context: ./services/smart-ai
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
