apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-depl
  namespace: expensio-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense
  template:
    metadata:
      labels:
        app: expense
    spec:
      containers:
        - name: expense
          image: ashuz057/expensio-expense
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: expense-secret
                  key: MONGO_URI
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: expense-secret
                  key: PORT
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: RABBITMQ_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: expense-srv
  namespace: expensio-dev
spec:
  selector:
    app: expense
  ports:
    - name: expense
      protocol: TCP
      port: 3000
      targetPort: 3000
