apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-depl
  namespace: expensio-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest # Kafka image
          ports:
            - containerPort: 9092 # Kafka port
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami/kafka
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-srv:9092
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-srv:2181 # Connecting to Zookeeper service
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKAJS_NO_PARTITIONER_WARNING
              value: "1"
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-srv
  namespace: expensio-dev
spec:
  selector:
    app: kafka
  ports:
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: 9092
