apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topic-creator
  namespace: expensio-dev
spec:
  template:
    spec:
      containers:
        - name: kafka-topic-creator
          image: bitnami/kafka:latest
          command:
            - sh
            - -c
            - |
              sleep 30;
              kafka-topics.sh --bootstrap-server kafka-srv:9092 --create --if-not-exists --topic user-events --replication-factor 1 --partitions 1;
              kafka-topics.sh --bootstrap-server kafka-srv:9092 --create --if-not-exists --topic expense-events --replication-factor 1 --partitions 1;
              kafka-topics.sh --bootstrap-server kafka-srv:9092 --create --if-not-exists --topic financial-data-events --replication-factor 1 --partitions 1;
              kafka-topics.sh --bootstrap-server kafka-srv:9092 --create --if-not-exists --topic income-events --replication-factor 1 --partitions 1;
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-srv:9092
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: zookeeper-srv:2181
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
      restartPolicy: Never
  backoffLimit: 1
