apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-depl
  namespace: expensio-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:latest # Zookeeper image
          ports:
            - containerPort: 2181 # Zookeeper port
          volumeMounts:
            - name: zookeeper-data
              mountPath: /bitnami/zookeeper
          env:
            - name: ZOO_PORT
              value: "2181"
            - name: ZOO_SERVER_ID
              value: "1"
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
      volumes:
        - name: zookeeper-data
          persistentVolumeClaim:
            claimName: zookeeper-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-srv
  namespace: expensio-dev
spec:
  selector:
    app: zookeeper
  ports:
    - name: zookeeper
      protocol: TCP
      port: 2181
      targetPort: 2181
